idf_component_register(
  SRCS
  "main.c"
  "LCD/Display/Display.c"
  "LCD/Touch/Touch.c"
  "LCD/Timer/Timer.c"
  "LVGL/lv_port.c"
  "UI/src/ui.c"
  "UI/src/ui_control_center.c"
  "UI/src/ui_data.c"
  "UI/src/ui_helpers.c"
  "UI/src/ui_screen_drive.c"
  "UI/src/ui_screen_weather.c"
  "UI/src/ui_screen_env.c"
  "UI/src/ui_screen_imu.c"
  "UI/src/ui_screen_iap.c"
  "UI/src/ui_screen_ota.c"
  "UI/src/ui_screen_wifi.c"
  "UI/src/ui_screen_w25.c"
  "UI/src/ui_screen_chat.c"
  "UI/src/ui_screen_sys.c"
  "UI/src/ui_standby.c"
  "UI/asset/icon_imu.c"
  "UI/asset/icon_download.c"
  "UI/asset/icon_environment.c"
  "UI/asset/icon_wifi.c"
  "UI/asset/weather_sunny.c"
  "UI/asset/weather_cloudy.c"
  "UI/asset/weather_overcast.c"
  "UI/asset/weather_rain.c"
  "UI/asset/weather_heavy_rain.c"
  "UI/asset/weather_snow.c"
  "UI/asset/weather_thunder.c"
  "UI/asset/weather_fog.c"
  "UI/asset/font_cn_supplement_14.c"
  "UI/asset/font_cn_supplement_16.c"
  "UI/asset/font_cn_weather_24.c"
  "UI/asset/PinF_font.c"
  "UI/asset/BK2.c"
  "UI/asset/lvgl_standby_320x240.c"
  "Can/Can.c"
  "HTTPS/WIFI/WiFi.c"
  "HTTPS/MQTT/http.c"
  "HTTPS/MQTT/httpBin.c"
  "W25Q/W25Q64.c"
  "LCD/Timer/LED.c"
  "HTTPS/MQTT/MQTT.c"
  "HTTPS/nowAPI/now.c"
  "HTTPS/qwWeather/weather.c"
  "HTTPS/ONENET/onenet.c"
  "HTTPS/ONENET/onenet_token.c"
  "HTTPS/LLM/LLM.c"
  INCLUDE_DIRS "." "HTTPS/LLM" "LCD/Display" "LCD/Touch" "LCD/Timer" "LCD" "LVGL" "UI/include" "HTTPS" "Can" "HTTPS/WIFI" "HTTPS/MQTT" "W25Q" "HTTPS/nowAPI" "HTTPS/qwWeather"
)
